// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Cache extends pulumi.CustomResource {
    /**
     * Get an existing Cache resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CacheState, opts?: pulumi.CustomResourceOptions): Cache {
        return new Cache(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'haproxy:index/cache:Cache';

    /**
     * Returns true if the given object is an instance of Cache.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Cache {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Cache.__pulumiType;
    }

    public readonly cacheId!: pulumi.Output<string>;
    /**
     * The max age of the Cache
     */
    public readonly maxAge!: pulumi.Output<number | undefined>;
    /**
     * The max object size of the Cache
     */
    public readonly maxObjectSize!: pulumi.Output<number | undefined>;
    /**
     * the max secondary entries of the Cache
     */
    public readonly maxSecondaryEntries!: pulumi.Output<number | undefined>;
    /**
     * The name of the Cache. It must be unique and cannot be changed.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The process vary of the Cache
     */
    public readonly processVary!: pulumi.Output<boolean | undefined>;
    /**
     * The total max size of the Cache
     */
    public readonly totalMaxSize!: pulumi.Output<number | undefined>;

    /**
     * Create a Cache resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CacheArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CacheArgs | CacheState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CacheState | undefined;
            resourceInputs["cacheId"] = state ? state.cacheId : undefined;
            resourceInputs["maxAge"] = state ? state.maxAge : undefined;
            resourceInputs["maxObjectSize"] = state ? state.maxObjectSize : undefined;
            resourceInputs["maxSecondaryEntries"] = state ? state.maxSecondaryEntries : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["processVary"] = state ? state.processVary : undefined;
            resourceInputs["totalMaxSize"] = state ? state.totalMaxSize : undefined;
        } else {
            const args = argsOrState as CacheArgs | undefined;
            resourceInputs["cacheId"] = args ? args.cacheId : undefined;
            resourceInputs["maxAge"] = args ? args.maxAge : undefined;
            resourceInputs["maxObjectSize"] = args ? args.maxObjectSize : undefined;
            resourceInputs["maxSecondaryEntries"] = args ? args.maxSecondaryEntries : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["processVary"] = args ? args.processVary : undefined;
            resourceInputs["totalMaxSize"] = args ? args.totalMaxSize : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Cache.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Cache resources.
 */
export interface CacheState {
    cacheId?: pulumi.Input<string>;
    /**
     * The max age of the Cache
     */
    maxAge?: pulumi.Input<number>;
    /**
     * The max object size of the Cache
     */
    maxObjectSize?: pulumi.Input<number>;
    /**
     * the max secondary entries of the Cache
     */
    maxSecondaryEntries?: pulumi.Input<number>;
    /**
     * The name of the Cache. It must be unique and cannot be changed.
     */
    name?: pulumi.Input<string>;
    /**
     * The process vary of the Cache
     */
    processVary?: pulumi.Input<boolean>;
    /**
     * The total max size of the Cache
     */
    totalMaxSize?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Cache resource.
 */
export interface CacheArgs {
    cacheId?: pulumi.Input<string>;
    /**
     * The max age of the Cache
     */
    maxAge?: pulumi.Input<number>;
    /**
     * The max object size of the Cache
     */
    maxObjectSize?: pulumi.Input<number>;
    /**
     * the max secondary entries of the Cache
     */
    maxSecondaryEntries?: pulumi.Input<number>;
    /**
     * The name of the Cache. It must be unique and cannot be changed.
     */
    name?: pulumi.Input<string>;
    /**
     * The process vary of the Cache
     */
    processVary?: pulumi.Input<boolean>;
    /**
     * The total max size of the Cache
     */
    totalMaxSize?: pulumi.Input<number>;
}
