// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getAcl(args: GetAclArgs, opts?: pulumi.InvokeOptions): Promise<GetAclResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("haproxy:index/getAcl:getAcl", {
        "id": args.id,
        "index": args.index,
        "name": args.name,
        "parentName": args.parentName,
        "parentType": args.parentType,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAcl.
 */
export interface GetAclArgs {
    id?: string;
    index?: number;
    name: string;
    parentName: string;
    parentType: string;
}

/**
 * A collection of values returned by getAcl.
 */
export interface GetAclResult {
    readonly id: string;
    readonly index?: number;
    readonly name: string;
    readonly parentName: string;
    readonly parentType: string;
}
export function getAclOutput(args: GetAclOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAclResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("haproxy:index/getAcl:getAcl", {
        "id": args.id,
        "index": args.index,
        "name": args.name,
        "parentName": args.parentName,
        "parentType": args.parentType,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAcl.
 */
export interface GetAclOutputArgs {
    id?: pulumi.Input<string>;
    index?: pulumi.Input<number>;
    name: pulumi.Input<string>;
    parentName: pulumi.Input<string>;
    parentType: pulumi.Input<string>;
}
