// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getBind(args: GetBindArgs, opts?: pulumi.InvokeOptions): Promise<GetBindResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("haproxy:index/getBind:getBind", {
        "id": args.id,
        "name": args.name,
        "parentName": args.parentName,
        "parentType": args.parentType,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBind.
 */
export interface GetBindArgs {
    id?: string;
    name: string;
    parentName: string;
    parentType: string;
}

/**
 * A collection of values returned by getBind.
 */
export interface GetBindResult {
    readonly id: string;
    readonly name: string;
    readonly parentName: string;
    readonly parentType: string;
}
export function getBindOutput(args: GetBindOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBindResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("haproxy:index/getBind:getBind", {
        "id": args.id,
        "name": args.name,
        "parentName": args.parentName,
        "parentType": args.parentType,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBind.
 */
export interface GetBindOutputArgs {
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    parentName: pulumi.Input<string>;
    parentType: pulumi.Input<string>;
}
