// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getDefaults(args: GetDefaultsArgs, opts?: pulumi.InvokeOptions): Promise<GetDefaultsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("haproxy:index/getDefaults:getDefaults", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDefaults.
 */
export interface GetDefaultsArgs {
    id?: string;
    name: string;
}

/**
 * A collection of values returned by getDefaults.
 */
export interface GetDefaultsResult {
    readonly id: string;
    readonly name: string;
}
export function getDefaultsOutput(args: GetDefaultsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDefaultsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("haproxy:index/getDefaults:getDefaults", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDefaults.
 */
export interface GetDefaultsOutputArgs {
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
