// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getFrontend(args: GetFrontendArgs, opts?: pulumi.InvokeOptions): Promise<GetFrontendResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("haproxy:index/getFrontend:getFrontend", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getFrontend.
 */
export interface GetFrontendArgs {
    id?: string;
    name: string;
}

/**
 * A collection of values returned by getFrontend.
 */
export interface GetFrontendResult {
    readonly id: string;
    readonly name: string;
}
export function getFrontendOutput(args: GetFrontendOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetFrontendResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("haproxy:index/getFrontend:getFrontend", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getFrontend.
 */
export interface GetFrontendOutputArgs {
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
