// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getGlobal(args: GetGlobalArgs, opts?: pulumi.InvokeOptions): Promise<GetGlobalResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("haproxy:index/getGlobal:getGlobal", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGlobal.
 */
export interface GetGlobalArgs {
    id?: string;
    name: string;
}

/**
 * A collection of values returned by getGlobal.
 */
export interface GetGlobalResult {
    readonly id: string;
    readonly name: string;
}
export function getGlobalOutput(args: GetGlobalOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetGlobalResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("haproxy:index/getGlobal:getGlobal", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGlobal.
 */
export interface GetGlobalOutputArgs {
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
