// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getHealth(args: GetHealthArgs, opts?: pulumi.InvokeOptions): Promise<GetHealthResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("haproxy:index/getHealth:getHealth", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getHealth.
 */
export interface GetHealthArgs {
    id?: string;
    name: string;
}

/**
 * A collection of values returned by getHealth.
 */
export interface GetHealthResult {
    readonly health: boolean;
    readonly id: string;
    readonly name: string;
}
export function getHealthOutput(args: GetHealthOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetHealthResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("haproxy:index/getHealth:getHealth", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getHealth.
 */
export interface GetHealthOutputArgs {
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
