// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getResolvers(args: GetResolversArgs, opts?: pulumi.InvokeOptions): Promise<GetResolversResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("haproxy:index/getResolvers:getResolvers", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getResolvers.
 */
export interface GetResolversArgs {
    id?: string;
    name: string;
}

/**
 * A collection of values returned by getResolvers.
 */
export interface GetResolversResult {
    readonly id: string;
    readonly name: string;
}
export function getResolversOutput(args: GetResolversOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetResolversResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("haproxy:index/getResolvers:getResolvers", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getResolvers.
 */
export interface GetResolversOutputArgs {
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
