// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getServer(args: GetServerArgs, opts?: pulumi.InvokeOptions): Promise<GetServerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("haproxy:index/getServer:getServer", {
        "id": args.id,
        "name": args.name,
        "parentName": args.parentName,
        "parentType": args.parentType,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getServer.
 */
export interface GetServerArgs {
    id?: string;
    name: string;
    parentName: string;
    parentType: string;
}

/**
 * A collection of values returned by getServer.
 */
export interface GetServerResult {
    readonly id: string;
    readonly name: string;
    readonly parentName: string;
    readonly parentType: string;
}
export function getServerOutput(args: GetServerOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetServerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("haproxy:index/getServer:getServer", {
        "id": args.id,
        "name": args.name,
        "parentName": args.parentName,
        "parentType": args.parentType,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getServer.
 */
export interface GetServerOutputArgs {
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    parentName: pulumi.Input<string>;
    parentType: pulumi.Input<string>;
}
