// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getUserlist(args: GetUserlistArgs, opts?: pulumi.InvokeOptions): Promise<GetUserlistResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("haproxy:index/getUserlist:getUserlist", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getUserlist.
 */
export interface GetUserlistArgs {
    id?: string;
    name: string;
}

/**
 * A collection of values returned by getUserlist.
 */
export interface GetUserlistResult {
    readonly id: string;
    readonly name: string;
}
export function getUserlistOutput(args: GetUserlistOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetUserlistResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("haproxy:index/getUserlist:getUserlist", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getUserlist.
 */
export interface GetUserlistOutputArgs {
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
