// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Userlist extends pulumi.CustomResource {
    /**
     * Get an existing Userlist resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserlistState, opts?: pulumi.CustomResourceOptions): Userlist {
        return new Userlist(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'haproxy:index/userlist:Userlist';

    /**
     * Returns true if the given object is an instance of Userlist.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Userlist {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Userlist.__pulumiType;
    }

    /**
     * The name of the Userlist. It must be unique
     */
    public readonly name!: pulumi.Output<string>;
    public readonly userlistId!: pulumi.Output<string>;

    /**
     * Create a Userlist resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: UserlistArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserlistArgs | UserlistState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserlistState | undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["userlistId"] = state ? state.userlistId : undefined;
        } else {
            const args = argsOrState as UserlistArgs | undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["userlistId"] = args ? args.userlistId : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Userlist.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Userlist resources.
 */
export interface UserlistState {
    /**
     * The name of the Userlist. It must be unique
     */
    name?: pulumi.Input<string>;
    userlistId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Userlist resource.
 */
export interface UserlistArgs {
    /**
     * The name of the Userlist. It must be unique
     */
    name?: pulumi.Input<string>;
    userlistId?: pulumi.Input<string>;
}
