// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserState, opts?: pulumi.CustomResourceOptions): User {
        return new User(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'haproxy:index/user:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    /**
     * The groups of the User
     */
    public readonly groups!: pulumi.Output<string | undefined>;
    /**
     * The password of the User
     */
    public readonly password!: pulumi.Output<string>;
    /**
     * The secure password of the User
     */
    public readonly securePassword!: pulumi.Output<boolean | undefined>;
    public readonly userId!: pulumi.Output<string>;
    /**
     * The userlist of the User
     */
    public readonly userlist!: pulumi.Output<string>;
    /**
     * The username of the User
     */
    public readonly username!: pulumi.Output<string>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserArgs | UserState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserState | undefined;
            resourceInputs["groups"] = state ? state.groups : undefined;
            resourceInputs["password"] = state ? state.password : undefined;
            resourceInputs["securePassword"] = state ? state.securePassword : undefined;
            resourceInputs["userId"] = state ? state.userId : undefined;
            resourceInputs["userlist"] = state ? state.userlist : undefined;
            resourceInputs["username"] = state ? state.username : undefined;
        } else {
            const args = argsOrState as UserArgs | undefined;
            if ((!args || args.password === undefined) && !opts.urn) {
                throw new Error("Missing required property 'password'");
            }
            if ((!args || args.userlist === undefined) && !opts.urn) {
                throw new Error("Missing required property 'userlist'");
            }
            if ((!args || args.username === undefined) && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["groups"] = args ? args.groups : undefined;
            resourceInputs["password"] = args ? args.password : undefined;
            resourceInputs["securePassword"] = args ? args.securePassword : undefined;
            resourceInputs["userId"] = args ? args.userId : undefined;
            resourceInputs["userlist"] = args ? args.userlist : undefined;
            resourceInputs["username"] = args ? args.username : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(User.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering User resources.
 */
export interface UserState {
    /**
     * The groups of the User
     */
    groups?: pulumi.Input<string>;
    /**
     * The password of the User
     */
    password?: pulumi.Input<string>;
    /**
     * The secure password of the User
     */
    securePassword?: pulumi.Input<boolean>;
    userId?: pulumi.Input<string>;
    /**
     * The userlist of the User
     */
    userlist?: pulumi.Input<string>;
    /**
     * The username of the User
     */
    username?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * The groups of the User
     */
    groups?: pulumi.Input<string>;
    /**
     * The password of the User
     */
    password: pulumi.Input<string>;
    /**
     * The secure password of the User
     */
    securePassword?: pulumi.Input<boolean>;
    userId?: pulumi.Input<string>;
    /**
     * The userlist of the User
     */
    userlist: pulumi.Input<string>;
    /**
     * The username of the User
     */
    username: pulumi.Input<string>;
}
